name: CI



# Controls when the action will run. 

on:

  # Triggers the workflow on push or pull request events but only for the main branch

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]



  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Edgeworkers
      uses: jdmevo123/akamai-edgeworker-action@1.1
      env:
        EDGERC: ${{ secrets.AKAMAI_EDGERC }}
      with:
        edgeworkersName: ${{ github.event.repository.name }}
        network: 'staging'
        groupid: '89177' #Akamai GroupID used for registering new edgeworkers 
